### ISSUE TITLE
usage example

### ISSUE THREAD

**Issue by wprayudo** [hamidreza-s/NanoChat#1]
any usage example please? I don't understand about broadcast means in nanochat -B usage.

Thanks

**Comment by hamidreza-s** [comment]
Hi,
Sorry for answering this late.

NanoChat uses UDP broadcasting for discovering other available (online) NanoChat nodes in the same subnet. It tries to find the broadcast IP itself, but also you can specify it by `-B {broadcast IP}` flag.
The `/probe` command inside NanoChat console discovers the subnet by sending a special UDP packet.

Also I've just updated the README.
